=== avithalker/TexasHoldemPoker/PokerEngine/src/generatedJaxb/TexaxHoldem.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 rel. 2 (http://www.altova.com) by mazuki (darksiderg) -->
<!--W3C Schema generated by XMLSpy v2008 rel. 2 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Type">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Computer"/>
				<xs:enumeration value="Human"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Structure">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="HandsCount"/>
				<xs:element ref="Buy"/>
				<xs:element ref="Blindes"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Small" type="xs:integer"/>
	<xs:element name="Players">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Player" minOccurs="3" maxOccurs="6"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Player">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Name"/>
				<xs:element ref="Type"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:integer" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Name" type="xs:string"/>
	<xs:element name="HandsCount" type="xs:integer"/>
	<xs:element name="GameType">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Basic"/>
				<xs:enumeration value="MultiPlayer"/>
				<xs:enumeration value="DynamicMultiPlayer"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="GameDescriptor">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="GameType"/>
				<xs:element ref="Structure"/>
				<xs:element ref="Players" minOccurs="0"/>
				<xs:element ref="DynamicPlayers" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="DynamicPlayers">
		<xs:complexType>
			<xs:attribute name="total-players" type="xs:byte" use="required"/>
			<xs:attribute name="game-title" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Buy" type="xs:integer"/>
	<xs:element name="Blindes">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Big"/>
				<xs:element ref="Small"/>
			</xs:sequence>
			<xs:attribute name="max-total-rounds" type="xs:integer" use="optional"/>
			<xs:attribute name="fixed" type="xs:boolean" use="required"/>
			<xs:attribute name="additions" type="xs:integer" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Big" type="xs:integer"/>
</xs:schema>

=== avithalker/TexasHoldemPoker/gamefiles/ex3-fixed.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2008 rel. 2 (http://www.altova.com)-->
<GameDescriptor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="TexaxHoldem.xsd">
	<GameType>DynamicMultiPlayer</GameType>
	<Structure>
		<HandsCount>12</HandsCount>
		<Buy>100</Buy>
		<Blindes fixed="true" additions="2" max-total-rounds="10">
			<Big>6</Big>
			<Small>3</Small>
		</Blindes>
	</Structure>	
	<DynamicPlayers game-title="sample game" total-players="6"/>
</GameDescriptor>
